### ISSUE TITLE
Implement create order endpoint

### ISSUE THREAD

**Issue by biblicalph** [biblicalph/pizza-delivery-api#20]
## Checklist
- [ ] Add the necessary labels

#### Issue Summary
Implement endpoint for creating new orders

#### Issue Description
1. The user should be logged in
2. The user's shopping cart should not be empty
3. The endpoint should return the order id on success

#### Todos
- [ ] Implement order model and service
- [ ] Implement endpoint for creating an order
